### ISSUE TITLE
Add documents source

### ISSUE THREAD

**Issue by lecw** [rali-udem/WiRe57#1]
Ce qui serait pratique ? Avoir les fichiers texte source des documents annotés.

À extraire / formater, soit à la main à partir du googledoc "Annotation WL+FG" (ou "Documents à annoter"), soit programmatiquement à partir de la ressource JSON.

**Comment by lecw** [comment]
e.g. this file contains all tokenized sentences, which is half good.

[wire_tokenized_sentences.txt](https://github.com/rali-udem/WiRe57/files/3390535/wire_tokenized_sentences.txt)

**Comment by rali-udem** [comment]
Commit 056fd7c15761d3240f055fee157cc5e7cd3d9113 now provides excerpts for the original documents, as well as their source URLs. Tokenization is left to the reader, which is not an enormous task given the number of documents.
